# Generated by Django 4.1.7 on 2023-03-23 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('clinic_address', models.CharField(max_length=200)),
                ('doctor_specilization', models.CharField(max_length=100)),
                ('certificate_photo', models.ImageField(upload_to='media/certificate/% y/% m/% d/')),
                ('rate', models.IntegerField()),
                ('work_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('university', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('patient_type_required', models.CharField(max_length=100)),
                ('university_id_photo', models.ImageField(upload_to='media/university_id/% y/% m/% d/')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='id_photo',
            field=models.ImageField(default='media\\id\\meow_lostcat (1).png', upload_to='media/id/%y/%m/%d/'),
        ),
    ]
