# Generated by Django 4.1.7 on 2023-03-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='media/id/meow_lostcat (1).png', upload_to='media/% email/'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='certificate_photo',
            field=models.ImageField(upload_to='media/certificate/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_id_photo',
            field=models.ImageField(upload_to='media/university_id/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_photo',
            field=models.ImageField(default='media/id/meow_lostcat (1).png', upload_to='media/id/%y/%m/%d/'),
        ),
    ]
