# Generated by Django 4.1.7 on 2023-03-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='media/id/meow_lostcat (1).png', upload_to='media/profiles_photo/% email'),
        ),
    ]
